name: Issue test
on: push
jobs:
  get-data:
    runs-on:  ubuntu-latest
    steps:
     - name: data
       uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
       with:
          script: |
            result="`; echo 1+1"
            echo ${{result}}
  issue-test:
    runs-on:  ubuntu-latest
    needs: get-data
    steps:
     - name: Comment Pull Request
       uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
       with:
          script: |
            const output = `${{ needs.get-data.outputs.result }}`;
            echo "this won't be executed, because of the issue";
