name: Issue test
on: push
jobs:
  data:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.data.outputs.result }}
    steps:
     - name: data
       id: data
       uses: actions/github-script@v6
       with:
          script: |
            const core = require('@actions/core');
            const result = "ยง";
            core.setOutput("result", result);

  issue-test:
    runs-on: ubuntu-latest
    needs: data
    steps:
     - name: MyNormalAction
       uses: actions/github-script@v6
       with:
          script: |
            const some_variable = "${{ needs.data.outputs.result }}";
            console.log(some_variable);
