name: Issue test
on: push
jobs:
  get-data:
    runs-on:  ubuntu-latest
    steps:
     - name: data
       id: get-data
       uses: actions/github-script@v6
       with:
          script: |
            result='`; echo 1+1';
            return { result };
  issue-test:
    runs-on:  ubuntu-latest
    needs: get-data
    steps:
     - name: Comment Pull Request
       uses: actions/github-script@v6
       with:
          script: |
            const output = `${{ needs.get-data.outputs.result }}`;
