name: Issue test
on: push
jobs:
  get-data:
    runs-on:  ubuntu-latest
    outputs:
      result: ${{ data.get-data.outputs.result }}
    steps:
     - name: data
       id: get-data
       uses: actions/github-script@v6
       with:
          script: |
            result='`; echo 1+1; echo `kek';
  issue-test:
    runs-on:  ubuntu-latest
    needs: get-data
    steps:
     - name: MyNormalAction
       uses: actions/github-script@v6
       with:
          script: |
            var some_variable = `${{ needs.get-data.outputs.result }}`;
