name: Issue test
on: push
jobs:
  data:
    runs-on:  ubuntu-latest
    outputs:
      result: ${{ steps.data.outputs.result }}
    steps:
     - name: data
       uses: actions/github-script@v6
       with:
          script: |
            result="ยง";
  issue-test:
    runs-on:  ubuntu-latest
    needs: data
    steps:
     - name: MyNormalAction
       uses: actions/github-script@v6
       with:
          script: |
            var some_variable = "${{ needs.get-data.outputs.result }}";
            echo "$some_variable";
